import type { Question, QuestionOption, BehaviorTags, RoundKind } from "./types";

// ─────────────────────────────────────────────────────────────
// ROOM — curated question bank (~175 items: decisions, dilemmas, votes,
// taste/values "compat probes" and accusation prompts)
//
// These are hand-written party-game prompts, NOT AI-generated.
// Every option carries behavioral metadata (tags, [-1..1]) that
// players never see. The engine uses tags to update the
// deterministic behavior model.
// ─────────────────────────────────────────────────────────────

function o(id: string, en: string, es: string, tags: BehaviorTags = {}): QuestionOption {
  return { id, label: { en, es }, tags };
}

interface QDef {
  id: string;
  category: Question["category"];
  kinds: RoundKind[];
  en: string;
  es: string;
  options: QuestionOption[];
  difficulty?: 1 | 2 | 3;
  socialSensitivity?: 0 | 1 | 2 | 3;
  theoryTestable?: boolean;
}

function q(d: QDef): Question {
  return {
    id: d.id,
    category: d.category,
    kinds: d.kinds,
    prompt: { en: d.en, es: d.es },
    options: d.options,
    difficulty: d.difficulty ?? 2,
    socialSensitivity: d.socialSensitivity ?? 0,
    theoryTestable: d.theoryTestable ?? false,
  };
}

export const QUESTIONS: Question[] = [
  // ---------------- MONEY ----------------
  q({
    id: "money_now_later",
    category: "money",
    kinds: ["individual"],
    en: "Take €500 right now, or €1,500 in two years?",
    es: "¿500 € ahora mismo, o 1.500 € dentro de dos años?",
    options: [
      o("A", "€500 now", "500 € ahora", { patience: -0.7, impulsivity: 0.5, greed: 0.2, risk: -0.1 }),
      o("B", "€1,500 in two years", "1.500 € en dos años", { patience: 0.8, consistency: 0.2, risk: 0.1 }),
    ],
    difficulty: 1,
  }),
  q({
    id: "money_split_pot",
    category: "money",
    kinds: ["individual"],
    en: "There's a €1,000 group pot. Do you split it evenly or claim a bigger share and risk it collapsing?",
    es: "Hay un bote común de 1.000 €. ¿Lo repartes a partes iguales o reclamas una parte mayor y arriesgas que se hunda?",
    options: [
      o("A", "Split evenly", "Repartir a partes iguales", { cooperation: 0.7, greed: -0.5, individualism: -0.4 }),
      o("B", "Claim more", "Reclamar más", { greed: 0.8, individualism: 0.6, cooperation: -0.5 }),
    ],
  }),
  q({
    id: "money_lottery_win",
    category: "money",
    kinds: ["individual"],
    en: "You win €10,000. First move?",
    es: "Ganas 10.000 €. ¿Primer movimiento?",
    options: [
      o("A", "Save all of it", "Ahorrarlo todo", { patience: 0.7, risk: -0.5, impulsivity: -0.5 }),
      o("B", "Invest it aggressively", "Invertirlo de forma agresiva", { risk: 0.8, greed: 0.4, patience: 0.2 }),
      o("C", "Spend it this month", "Gastarlo este mes", { impulsivity: 0.8, patience: -0.7, risk: 0.3 }),
    ],
  }),
  q({
    id: "money_free_lunch",
    category: "money",
    kinds: ["individual", "majority_minority"],
    en: "A stranger offers you €50 to skip the queue in front of everyone. Do you take it?",
    es: "Un desconocido te ofrece 50 € por colarte delante de todos. ¿Lo aceptas?",
    options: [
      o("A", "Take the €50", "Aceptar los 50 €", { individualism: 0.6, greed: 0.5, socialAlignment: -0.4 }),
      o("B", "Refuse", "Rechazar", { socialAlignment: 0.5, individualism: -0.4, greed: -0.4 }),
    ],
    socialSensitivity: 1,
  }),
  q({
    id: "money_debt_friend",
    category: "money",
    kinds: ["individual"],
    en: "A friend owes you €200 and 'forgot'. Do you ask for it back?",
    es: "Un amigo te debe 200 € y 'se le ha olvidado'. ¿Se lo reclamas?",
    options: [
      o("A", "Ask directly", "Reclamar directamente", { individualism: 0.4, consistency: 0.3, greed: 0.3 }),
      o("B", "Let it slide", "Dejarlo pasar", { loyalty: 0.5, cooperation: 0.4, greed: -0.4 }),
    ],
    socialSensitivity: 1,
  }),
  q({
    id: "money_insurance",
    category: "money",
    kinds: ["individual"],
    en: "Pay €30/month for insurance you'll probably never use?",
    es: "¿Pagar 30 €/mes por un seguro que probablemente nunca usarás?",
    options: [
      o("A", "Yes, peace of mind", "Sí, por tranquilidad", { risk: -0.7, patience: 0.3, impulsivity: -0.3 }),
      o("B", "No, I'll take the chance", "No, me arriesgo", { risk: 0.7, impulsivity: 0.3 }),
    ],
    difficulty: 1,
  }),
  q({
    id: "money_raise_or_time",
    category: "money",
    kinds: ["individual"],
    en: "Your boss offers a 15% raise OR one extra day off per week. Pick one.",
    es: "Tu jefe te ofrece un 15% de subida O un día libre extra a la semana. Elige.",
    options: [
      o("A", "The raise", "La subida", { greed: 0.6, competitiveness: 0.4, individualism: 0.2 }),
      o("B", "The day off", "El día libre", { patience: 0.4, greed: -0.4, competitiveness: -0.3 }),
    ],
    difficulty: 1,
  }),

  // ---------------- RISK ----------------
  q({
    id: "risk_safe_vs_gamble",
    category: "risk",
    kinds: ["majority_minority", "individual"],
    en: "Choose one.",
    es: "Elige una.",
    options: [
      o("A", "Take 100 guaranteed points", "100 puntos garantizados", { risk: -0.8, conformity: 0.1 }),
      o("B", "Risk the 100 to win 300", "Arriesgar los 100 para ganar 300", { risk: 0.8, competitiveness: 0.4 }),
    ],
    difficulty: 1,
  }),
  q({
    id: "risk_double_or_nothing",
    category: "risk",
    kinds: ["majority_minority", "individual"],
    en: "You have 200 points. Flip a coin: double them or lose half?",
    es: "Tienes 200 puntos. Lanza una moneda: los doblas o pierdes la mitad.",
    options: [
      o("A", "Keep the 200", "Quedarte con los 200", { risk: -0.7, patience: 0.3 }),
      o("B", "Flip", "Lanzar", { risk: 0.8, impulsivity: 0.4 }),
    ],
  }),
  q({
    id: "risk_skydive",
    category: "risk",
    kinds: ["individual"],
    en: "Free skydiving trip tomorrow. In or out?",
    es: "Viaje gratis de paracaidismo mañana. ¿Te apuntas?",
    options: [
      o("A", "In", "Me apunto", { risk: 0.8, impulsivity: 0.5 }),
      o("B", "Out", "Paso", { risk: -0.7, impulsivity: -0.3 }),
    ],
    difficulty: 1,
  }),
  q({
    id: "risk_startup_job",
    category: "risk",
    kinds: ["individual"],
    en: "Stable job with steady pay, or a startup that might 10x or die in a year?",
    es: "¿Trabajo estable con sueldo fijo, o una startup que puede multiplicarse por 10 o morir en un año?",
    options: [
      o("A", "Stable job", "Trabajo estable", { risk: -0.7, patience: 0.4, consistency: 0.4 }),
      o("B", "Startup", "Startup", { risk: 0.8, competitiveness: 0.4, greed: 0.3 }),
    ],
  }),
  q({
    id: "risk_unknown_door",
    category: "risk",
    kinds: ["individual", "majority_minority"],
    en: "Two doors. One hides a small guaranteed prize, one is a total mystery. Which?",
    es: "Dos puertas. Una esconde un premio pequeño seguro, la otra es un misterio total. ¿Cuál?",
    options: [
      o("A", "Guaranteed prize", "Premio seguro", { risk: -0.6, patience: 0.2 }),
      o("B", "Mystery door", "Puerta misteriosa", { risk: 0.7, impulsivity: 0.4 }),
    ],
  }),
  q({
    id: "risk_spicy_food",
    category: "risk",
    kinds: ["individual"],
    en: "The waiter dares the table to order the 'do not attempt' hot sauce. You?",
    es: "El camarero reta a la mesa a pedir la salsa picante de 'no lo intentes'. ¿Tú?",
    options: [
      o("A", "I'm doing it", "Yo lo hago", { risk: 0.6, competitiveness: 0.4, impulsivity: 0.4 }),
      o("B", "Absolutely not", "Ni de broma", { risk: -0.6 }),
    ],
    difficulty: 1,
    socialSensitivity: 1,
  }),
  q({
    id: "risk_all_in_final",
    category: "risk",
    kinds: ["individual", "majority_minority"],
    en: "Final round of a game. Bet everything for a shot at first, or lock in second place?",
    es: "Última ronda de una partida. ¿Apostar todo por el primer puesto, o asegurar el segundo?",
    options: [
      o("A", "Lock in second", "Asegurar el segundo", { risk: -0.6, competitiveness: -0.2, patience: 0.3 }),
      o("B", "Bet everything", "Apostar todo", { risk: 0.8, competitiveness: 0.7 }),
    ],
  }),

  // ---------------- STRATEGY ----------------
  q({
    id: "strat_long_game",
    category: "strategy",
    kinds: ["individual"],
    en: "Win small now, or set up a move that only pays off in three rounds?",
    es: "¿Ganar poco ahora, o preparar una jugada que solo da fruto dentro de tres rondas?",
    options: [
      o("A", "Win small now", "Ganar poco ahora", { patience: -0.5, impulsivity: 0.4, competitiveness: 0.3 }),
      o("B", "Play the long game", "Jugar a largo plazo", { patience: 0.7, consistency: 0.4 }),
    ],
  }),
  q({
    id: "strat_hide_strength",
    category: "strategy",
    kinds: ["individual"],
    en: "You're secretly winning. Do you reveal it or keep a low profile?",
    es: "Vas ganando en secreto. ¿Lo revelas o mantienes un perfil bajo?",
    options: [
      o("A", "Reveal it", "Revelarlo", { competitiveness: 0.5, individualism: 0.3, impulsivity: 0.3 }),
      o("B", "Stay quiet", "Mantener silencio", { patience: 0.5, consistency: 0.3, competitiveness: 0.2 }),
    ],
  }),
  q({
    id: "strat_kingmaker",
    category: "strategy",
    kinds: ["individual"],
    en: "You can't win, but you can decide who does. Do you help the leader or the underdog?",
    es: "No puedes ganar, pero puedes decidir quién gana. ¿Ayudas al líder o al que va último?",
    options: [
      o("A", "Help the leader", "Ayudar al líder", { socialAlignment: 0.3, conformity: 0.4 }),
      o("B", "Help the underdog", "Ayudar al último", { contrarianism: 0.5, loyalty: 0.3 }),
    ],
  }),
  q({
    id: "strat_sacrifice_points",
    category: "strategy",
    kinds: ["individual"],
    en: "Give up 100 points now to block the current leader from scoring. Do it?",
    es: "Renuncia a 100 puntos ahora para impedir que el líder actual puntúe. ¿Lo haces?",
    options: [
      o("A", "Yes, block them", "Sí, bloquearle", { competitiveness: 0.7, contrarianism: 0.3 }),
      o("B", "No, keep my points", "No, me quedo mis puntos", { individualism: 0.5, greed: 0.4 }),
    ],
  }),
  q({
    id: "strat_information",
    category: "strategy",
    kinds: ["individual"],
    en: "You learn a secret that helps you but hurts a friend if you use it. Use it?",
    es: "Descubres un secreto que te beneficia pero perjudica a un amigo si lo usas. ¿Lo usas?",
    options: [
      o("A", "Use it", "Usarlo", { individualism: 0.6, competitiveness: 0.5, loyalty: -0.5 }),
      o("B", "Don't", "No usarlo", { loyalty: 0.7, cooperation: 0.4 }),
    ],
    socialSensitivity: 1,
  }),
  q({
    id: "strat_copy_or_lead",
    category: "strategy",
    kinds: ["individual", "majority_minority"],
    en: "In a new situation, do you copy what works for others or invent your own approach?",
    es: "Ante algo nuevo, ¿copias lo que le funciona a otros o inventas tu propio enfoque?",
    options: [
      o("A", "Copy what works", "Copiar lo que funciona", { conformity: 0.6, patience: 0.2, risk: -0.3 }),
      o("B", "Invent my own", "Inventar el mío", { contrarianism: 0.5, risk: 0.4, individualism: 0.4 }),
    ],
  }),
  q({
    id: "strat_early_alliance",
    category: "strategy",
    kinds: ["individual"],
    en: "Early in the game, do you lock in an alliance or stay flexible?",
    es: "Al principio del juego, ¿cierras una alianza o te mantienes flexible?",
    options: [
      o("A", "Lock in an alliance", "Cerrar una alianza", { loyalty: 0.6, cooperation: 0.5, consistency: 0.3 }),
      o("B", "Stay flexible", "Mantenerme flexible", { individualism: 0.5, contrarianism: 0.3 }),
    ],
  }),

  // ---------------- COMPETITION ----------------
  q({
    id: "comp_win_ugly",
    category: "competition",
    kinds: ["individual"],
    en: "Would you rather win by playing dirty, or lose with a clean game?",
    es: "¿Prefieres ganar jugando sucio, o perder con un juego limpio?",
    options: [
      o("A", "Win dirty", "Ganar sucio", { competitiveness: 0.8, loyalty: -0.3, cooperation: -0.4 }),
      o("B", "Lose clean", "Perder limpio", { competitiveness: -0.4, loyalty: 0.4, consistency: 0.3 }),
    ],
  }),
  q({
    id: "comp_rematch",
    category: "competition",
    kinds: ["individual"],
    en: "You lost badly. Demand a rematch tonight, or let it go?",
    es: "Has perdido feo. ¿Exiges la revancha esta noche, o lo dejas pasar?",
    options: [
      o("A", "Rematch now", "Revancha ya", { competitiveness: 0.8, impulsivity: 0.4 }),
      o("B", "Let it go", "Dejarlo pasar", { competitiveness: -0.4, patience: 0.4 }),
    ],
    difficulty: 1,
  }),
  q({
    id: "comp_help_rival",
    category: "competition",
    kinds: ["individual"],
    en: "Your closest rival asks you to explain the rules they missed. Help them?",
    es: "Tu rival más cercano te pide que le expliques las reglas que se perdió. ¿Le ayudas?",
    options: [
      o("A", "Explain fully", "Explicárselo todo", { cooperation: 0.6, loyalty: 0.4, competitiveness: -0.3 }),
      o("B", "Stay vague", "Quedarte impreciso", { competitiveness: 0.6, individualism: 0.4 }),
    ],
  }),
  q({
    id: "comp_public_score",
    category: "competition",
    kinds: ["individual", "majority_minority"],
    en: "Would you play better if everyone could see your score at all times?",
    es: "¿Jugarías mejor si todos vieran tu puntuación en todo momento?",
    options: [
      o("A", "Yes, pressure helps me", "Sí, la presión me ayuda", { competitiveness: 0.7, risk: 0.2 }),
      o("B", "No, I'd rather hide it", "No, prefiero esconderla", { competitiveness: -0.2, patience: 0.3 }),
    ],
  }),
  q({
    id: "comp_beat_friend",
    category: "competition",
    kinds: ["individual"],
    en: "It's you vs your best friend for the win. How hard do you go?",
    es: "Sois tú contra tu mejor amigo por la victoria. ¿Con cuántas ganas vas?",
    options: [
      o("A", "Full force", "Con todo", { competitiveness: 0.8, loyalty: -0.2 }),
      o("B", "Ease off a little", "Aflojar un poco", { loyalty: 0.6, competitiveness: -0.4, cooperation: 0.3 }),
    ],
  }),
  q({
    id: "comp_trash_talk",
    category: "competition",
    kinds: ["individual"],
    en: "Trash talk during games: essential or annoying?",
    es: "Picarse durante las partidas: ¿esencial o molesto?",
    options: [
      o("A", "Essential", "Esencial", { competitiveness: 0.6, impulsivity: 0.4, socialAlignment: 0.2 }),
      o("B", "Annoying", "Molesto", { competitiveness: -0.3, consistency: 0.3 }),
    ],
    difficulty: 1,
  }),
  q({
    id: "comp_solo_or_team",
    category: "competition",
    kinds: ["individual", "majority_minority"],
    en: "Would you rather come first alone, or second as part of the winning team?",
    es: "¿Prefieres quedar primero en solitario, o segundo dentro del equipo ganador?",
    options: [
      o("A", "First alone", "Primero en solitario", { individualism: 0.7, competitiveness: 0.6 }),
      o("B", "Second with the team", "Segundo con el equipo", { cooperation: 0.6, socialAlignment: 0.5, individualism: -0.5 }),
    ],
  }),

  // ---------------- LOYALTY ----------------
  q({
    id: "loyal_cover_friend",
    category: "loyalty",
    kinds: ["individual"],
    en: "A friend messed up at work. Your boss asks you directly what happened. You...",
    es: "Un amigo la ha liado en el trabajo. Tu jefe te pregunta directamente qué pasó. Tú...",
    options: [
      o("A", "Cover for them", "Cubrirle", { loyalty: 0.8, cooperation: 0.3, consistency: -0.2 }),
      o("B", "Tell the truth", "Decir la verdad", { loyalty: -0.4, consistency: 0.5, individualism: 0.3 }),
    ],
    socialSensitivity: 1,
  }),
  q({
    id: "loyal_old_new",
    category: "loyalty",
    kinds: ["individual"],
    en: "New group, better opportunities. Do you bring your old crew along or move on?",
    es: "Grupo nuevo, mejores oportunidades. ¿Te llevas a tu gente de siempre o pasas página?",
    options: [
      o("A", "Bring them along", "Llevármelos", { loyalty: 0.8, cooperation: 0.4 }),
      o("B", "Move on", "Pasar página", { individualism: 0.6, loyalty: -0.5, competitiveness: 0.3 }),
    ],
  }),
  q({
    id: "loyal_defend_absent",
    category: "loyalty",
    kinds: ["individual"],
    en: "The group starts roasting someone who left the room. You...",
    es: "El grupo empieza a rajar de alguien que ha salido de la sala. Tú...",
    options: [
      o("A", "Defend them", "Le defiendes", { loyalty: 0.7, contrarianism: 0.3, socialAlignment: -0.2 }),
      o("B", "Join in", "Te unes", { socialAlignment: 0.5, conformity: 0.5, loyalty: -0.4 }),
    ],
    socialSensitivity: 2,
  }),
  q({
    id: "loyal_keep_secret",
    category: "loyalty",
    kinds: ["individual"],
    en: "A friend tells you a secret that the whole group would love to know. Do you keep it?",
    es: "Un amigo te cuenta un secreto que al grupo entero le encantaría saber. ¿Lo guardas?",
    options: [
      o("A", "Keep it locked", "Guardarlo a cal y canto", { loyalty: 0.8, consistency: 0.4 }),
      o("B", "It'll probably slip out", "Probablemente se me escape", { loyalty: -0.4, impulsivity: 0.6, socialAlignment: 0.3 }),
    ],
    socialSensitivity: 1,
  }),
  q({
    id: "loyal_ride_or_die",
    category: "loyalty",
    kinds: ["individual"],
    en: "A friend makes a decision you think is a mistake. Do you back them anyway?",
    es: "Un amigo toma una decisión que crees que es un error. ¿Le apoyas igualmente?",
    options: [
      o("A", "Back them fully", "Apoyarle del todo", { loyalty: 0.8, cooperation: 0.3, contrarianism: -0.2 }),
      o("B", "Tell them they're wrong", "Decirle que se equivoca", { consistency: 0.5, individualism: 0.4, contrarianism: 0.3 }),
    ],
  }),
  q({
    id: "loyal_credit",
    category: "loyalty",
    kinds: ["individual"],
    en: "You and a teammate did the work together, but only you got praised. You...",
    es: "Tú y un compañero hicisteis el trabajo juntos, pero solo te felicitaron a ti. Tú...",
    options: [
      o("A", "Share the credit", "Repartir el mérito", { loyalty: 0.7, cooperation: 0.6, greed: -0.4 }),
      o("B", "Take the win", "Quedarte la victoria", { individualism: 0.6, competitiveness: 0.5, greed: 0.4 }),
    ],
  }),
  q({
    id: "loyal_group_chat",
    category: "loyalty",
    kinds: ["individual"],
    en: "Someone screenshots a private chat to prove a point in the group. Fair game?",
    es: "Alguien hace captura de un chat privado para demostrar algo en el grupo. ¿Vale?",
    options: [
      o("A", "Not okay", "No vale", { loyalty: 0.6, consistency: 0.4 }),
      o("B", "Fair game", "Vale", { individualism: 0.5, competitiveness: 0.3, loyalty: -0.4 }),
    ],
    socialSensitivity: 1,
  }),

  // ---------------- TRUST ----------------
  q({
    id: "trust_decide_for_group",
    category: "trust",
    kinds: ["group_vote", "trust"],
    en: "Who would you trust to make an important decision for the whole group?",
    es: "¿En quién confiarías para tomar una decisión importante por todo el grupo?",
    options: [],
    theoryTestable: true,
  }),
  q({
    id: "trust_hold_money",
    category: "trust",
    kinds: ["group_vote", "trust"],
    en: "You have to hand your winnings to one person until the end. Who?",
    es: "Tienes que dejar tus ganancias a una persona hasta el final. ¿A quién?",
    options: [],
    theoryTestable: true,
  }),
  q({
    id: "trust_secret_keeper",
    category: "trust",
    kinds: ["group_vote", "trust"],
    en: "Who in this room actually keeps a secret?",
    es: "¿Quién de esta sala guarda de verdad un secreto?",
    options: [],
    theoryTestable: true,
  }),
  q({
    id: "trust_back_you_up",
    category: "trust",
    kinds: ["group_vote", "trust"],
    en: "Things go wrong. Who has your back without asking questions?",
    es: "Las cosas se tuercen. ¿Quién te cubre sin hacer preguntas?",
    options: [],
    theoryTestable: true,
  }),
  q({
    id: "trust_lie_detector",
    category: "trust",
    kinds: ["group_vote"],
    en: "Who is the hardest person here to read?",
    es: "¿Quién es la persona más difícil de leer de aquí?",
    options: [],
    theoryTestable: true,
  }),
  q({
    id: "trust_borrow_car",
    category: "trust",
    kinds: ["group_vote", "trust"],
    en: "Who could borrow something valuable of yours and you wouldn't worry?",
    es: "¿A quién le dejarías algo valioso tuyo sin preocuparte?",
    options: [],
    theoryTestable: true,
  }),
  q({
    id: "trust_advice",
    category: "trust",
    kinds: ["group_vote"],
    en: "Big life decision tomorrow. Whose advice do you actually take?",
    es: "Decisión importante de vida mañana. ¿El consejo de quién te tomas en serio?",
    options: [],
    theoryTestable: true,
  }),

  // ---------------- COOPERATION ----------------
  q({
    id: "coop_prisoner",
    category: "cooperation",
    kinds: ["social_dilemma"],
    en: "Cooperate for +200 each. Betray for +500 (and they get 0). If you both betray, +50 each.",
    es: "Coopera y +200 cada uno. Traiciona y +500 (el otro se queda a 0). Si ambos traicionáis, +50 cada uno.",
    options: [
      o("A", "Cooperate", "Cooperar", { cooperation: 0.8, loyalty: 0.4, greed: -0.3 }),
      o("B", "Betray", "Traicionar", { cooperation: -0.7, individualism: 0.6, greed: 0.6 }),
    ],
    difficulty: 3,
    theoryTestable: true,
  }),
  q({
    id: "coop_carry_team",
    category: "cooperation",
    kinds: ["individual"],
    en: "Group task, uneven effort. Do you carry the slackers or do only your share?",
    es: "Tarea de grupo, esfuerzo desigual. ¿Cargas con los vagos o haces solo tu parte?",
    options: [
      o("A", "Carry them", "Cargar con ellos", { cooperation: 0.7, patience: 0.4, individualism: -0.4 }),
      o("B", "Only my share", "Solo mi parte", { individualism: 0.6, consistency: 0.3, cooperation: -0.4 }),
    ],
  }),
  q({
    id: "coop_shared_prize",
    category: "cooperation",
    kinds: ["social_dilemma"],
    en: "You and another player can lock in +150 each by both choosing 'share'. Choosing 'grab' gives you +250 only if the other chose 'share'.",
    es: "Tú y otro jugador aseguráis +150 cada uno si ambos elegís 'compartir'. Elegir 'coger' te da +250 solo si el otro eligió 'compartir'.",
    options: [
      o("A", "Share", "Compartir", { cooperation: 0.7, loyalty: 0.3 }),
      o("B", "Grab", "Coger", { greed: 0.7, individualism: 0.6, cooperation: -0.6 }),
    ],
    difficulty: 3,
    theoryTestable: true,
  }),
  q({
    id: "coop_volunteer",
    category: "cooperation",
    kinds: ["individual", "majority_minority"],
    en: "Someone has to lose 50 points so the group gains 200. Do you volunteer?",
    es: "Alguien tiene que perder 50 puntos para que el grupo gane 200. ¿Te ofreces?",
    options: [
      o("A", "I'll do it", "Lo hago yo", { cooperation: 0.8, loyalty: 0.4, individualism: -0.5 }),
      o("B", "Let someone else", "Que lo haga otro", { individualism: 0.5, greed: 0.3 }),
    ],
  }),
  q({
    id: "coop_split_bill",
    category: "cooperation",
    kinds: ["individual"],
    en: "The bill arrives. You had a salad, others had lobster. Split evenly or pay your own?",
    es: "Llega la cuenta. Tú una ensalada, otros langosta. ¿Repartir a partes iguales o pagar lo tuyo?",
    options: [
      o("A", "Split evenly", "A partes iguales", { cooperation: 0.6, socialAlignment: 0.5, greed: -0.3 }),
      o("B", "Pay my own", "Pagar lo mío", { individualism: 0.5, consistency: 0.4, greed: 0.3 }),
    ],
    difficulty: 1,
  }),
  q({
    id: "coop_last_slice",
    category: "cooperation",
    kinds: ["individual"],
    en: "Last slice of pizza, nobody's claimed it. You...",
    es: "Último trozo de pizza, nadie lo ha reclamado. Tú...",
    options: [
      o("A", "Offer it around", "Ofrecerlo", { cooperation: 0.5, socialAlignment: 0.5, greed: -0.4 }),
      o("B", "Take it fast", "Cogerlo rápido", { impulsivity: 0.5, greed: 0.5, individualism: 0.4 }),
    ],
    difficulty: 1,
  }),
  q({
    id: "coop_help_or_win",
    category: "cooperation",
    kinds: ["social_dilemma"],
    en: "You can spend your turn helping a partner catch up, or pulling ahead alone.",
    es: "Puedes usar tu turno en ayudar a un compañero a remontar, o en despegarte tú solo.",
    options: [
      o("A", "Help the partner", "Ayudar al compañero", { cooperation: 0.8, loyalty: 0.5, competitiveness: -0.3 }),
      o("B", "Pull ahead alone", "Despegarme solo", { competitiveness: 0.7, individualism: 0.6 }),
    ],
    theoryTestable: true,
  }),

  // ---------------- GROUP BEHAVIOR ----------------
  q({
    id: "grp_follow_plans",
    category: "group_behavior",
    kinds: ["individual", "majority_minority"],
    en: "The group changes the plan last minute. You...",
    es: "El grupo cambia el plan a última hora. Tú...",
    options: [
      o("A", "Go with it", "Seguir la corriente", { conformity: 0.7, socialAlignment: 0.6, patience: 0.3 }),
      o("B", "Push back", "Plantarte", { contrarianism: 0.6, individualism: 0.4, impulsivity: 0.3 }),
    ],
    difficulty: 1,
  }),
  q({
    id: "grp_restaurant",
    category: "group_behavior",
    kinds: ["individual", "majority_minority"],
    en: "Everyone's ordering the same dish. Do you get it too or order something different?",
    es: "Todos piden el mismo plato. ¿Lo pides también o algo distinto?",
    options: [
      o("A", "Get the same", "Pedir lo mismo", { conformity: 0.7, socialAlignment: 0.5 }),
      o("B", "Order different", "Pedir algo distinto", { contrarianism: 0.6, individualism: 0.5 }),
    ],
    difficulty: 1,
  }),
  q({
    id: "grp_silence",
    category: "group_behavior",
    kinds: ["individual"],
    en: "The group agrees on something you think is wrong. Nobody else objects. You...",
    es: "El grupo se pone de acuerdo en algo que crees que está mal. Nadie más objeta. Tú...",
    options: [
      o("A", "Speak up alone", "Hablar aunque estés solo", { contrarianism: 0.8, individualism: 0.5, conformity: -0.6 }),
      o("B", "Stay quiet", "Callarte", { conformity: 0.6, socialAlignment: 0.4, patience: 0.2 }),
    ],
  }),
  q({
    id: "grp_trendsetter",
    category: "group_behavior",
    kinds: ["individual"],
    en: "In your friend group, are you usually the one starting things or the one joining in?",
    es: "En tu grupo de amigos, ¿sueles ser quien propone o quien se apunta?",
    options: [
      o("A", "I start things", "Yo propongo", { individualism: 0.5, competitiveness: 0.3, impulsivity: 0.3 }),
      o("B", "I join in", "Yo me apunto", { conformity: 0.5, socialAlignment: 0.5, cooperation: 0.3 }),
    ],
    difficulty: 1,
  }),
  q({
    id: "grp_vote_publicly",
    category: "group_behavior",
    kinds: ["majority_minority"],
    en: "Vote out loud, in order. Does hearing others' votes change yours?",
    es: "Votad en voz alta, por turnos. ¿Oír los votos de otros cambia el tuyo?",
    options: [
      o("A", "Yes, sometimes", "Sí, a veces", { conformity: 0.7, socialAlignment: 0.5, consistency: -0.3 }),
      o("B", "Never", "Nunca", { consistency: 0.6, contrarianism: 0.4, individualism: 0.3 }),
    ],
  }),
  q({
    id: "grp_peer_pressure",
    category: "group_behavior",
    kinds: ["individual"],
    en: "Everyone's staying for one more round. You're tired. You...",
    es: "Todos se quedan a una ronda más. Estás cansado. Tú...",
    options: [
      o("A", "Stay anyway", "Quedarte igual", { conformity: 0.6, socialAlignment: 0.6 }),
      o("B", "Leave", "Irte", { individualism: 0.6, consistency: 0.4, contrarianism: 0.3 }),
    ],
    difficulty: 1,
  }),
  q({
    id: "grp_group_photo",
    category: "group_behavior",
    kinds: ["individual"],
    en: "Group photo: front and center, or edge of the frame?",
    es: "Foto de grupo: ¿en el centro delante, o al borde del encuadre?",
    options: [
      o("A", "Front and center", "En el centro", { competitiveness: 0.4, individualism: 0.4, socialAlignment: 0.3 }),
      o("B", "Edge of the frame", "Al borde", { individualism: 0.2, competitiveness: -0.3 }),
    ],
    difficulty: 1,
  }),

  // ---------------- FUNNY DILEMMAS ----------------
  q({
    id: "fun_invisible",
    category: "funny_dilemma",
    kinds: ["individual"],
    en: "One hour invisible. Prank your friends or spy on your enemies?",
    es: "Una hora invisible. ¿Gastar bromas a tus amigos o espiar a tus enemigos?",
    options: [
      o("A", "Prank friends", "Bromas a los amigos", { impulsivity: 0.6, socialAlignment: 0.3, competitiveness: 0.2 }),
      o("B", "Spy on enemies", "Espiar enemigos", { competitiveness: 0.5, individualism: 0.4, contrarianism: 0.2 }),
    ],
    difficulty: 1,
  }),
  q({
    id: "fun_last_meal",
    category: "funny_dilemma",
    kinds: ["individual"],
    en: "You can only eat one food forever. Safe favorite or a wildcard you might grow to love?",
    es: "Solo puedes comer un alimento para siempre. ¿Tu favorito seguro o un comodín que quizá acabes amando?",
    options: [
      o("A", "Safe favorite", "Favorito seguro", { risk: -0.6, consistency: 0.5, patience: 0.2 }),
      o("B", "Wildcard", "Comodín", { risk: 0.6, impulsivity: 0.4 }),
    ],
    difficulty: 1,
  }),
  q({
    id: "fun_fame",
    category: "funny_dilemma",
    kinds: ["individual"],
    en: "Be famous for something embarrassing, or completely unknown forever?",
    es: "¿Ser famoso por algo vergonzoso, o completamente desconocido para siempre?",
    options: [
      o("A", "Famous, embarrassing", "Famoso y vergonzoso", { competitiveness: 0.4, risk: 0.4, socialAlignment: 0.3 }),
      o("B", "Unknown forever", "Desconocido para siempre", { individualism: 0.3, risk: -0.4 }),
    ],
    difficulty: 1,
  }),
  q({
    id: "fun_time_travel",
    category: "funny_dilemma",
    kinds: ["individual"],
    en: "One trip: 100 years back or 100 years forward?",
    es: "Un viaje: ¿100 años atrás o 100 años adelante?",
    options: [
      o("A", "Back", "Atrás", { patience: 0.3, risk: -0.2, consistency: 0.3 }),
      o("B", "Forward", "Adelante", { risk: 0.5, patience: 0.4 }),
    ],
    difficulty: 1,
  }),
  q({
    id: "fun_superpower",
    category: "funny_dilemma",
    kinds: ["individual", "majority_minority"],
    en: "Read minds, or always know when someone's lying?",
    es: "¿Leer mentes, o saber siempre cuándo alguien miente?",
    options: [
      o("A", "Read minds", "Leer mentes", { trust: -0.3, individualism: 0.3, competitiveness: 0.3 }),
      o("B", "Detect lies", "Detectar mentiras", { trust: -0.2, consistency: 0.4 }),
    ],
    difficulty: 1,
  }),
  q({
    id: "fun_group_stranded",
    category: "funny_dilemma",
    kinds: ["group_vote"],
    en: "The group is stranded on an island. Who's in charge by tomorrow morning?",
    es: "El grupo está atrapado en una isla. ¿Quién manda mañana por la mañana?",
    options: [],
    theoryTestable: true,
  }),
  q({
    id: "fun_worst_roommate",
    category: "funny_dilemma",
    kinds: ["group_vote"],
    en: "Who here would be the most chaotic roommate?",
    es: "¿Quién de aquí sería el compañero de piso más caótico?",
    options: [],
    socialSensitivity: 1,
  }),

  // ---------------- SOCIAL CHOICES ----------------
  q({
    id: "soc_plus_one",
    category: "social_choice",
    kinds: ["group_vote"],
    en: "One free ticket to the best night of the year. Who's your plus one?",
    es: "Una entrada gratis para la mejor noche del año. ¿A quién te llevas?",
    options: [],
    socialSensitivity: 1,
    theoryTestable: true,
  }),
  q({
    id: "soc_road_trip",
    category: "social_choice",
    kinds: ["group_vote"],
    en: "12-hour road trip, one passenger seat. Who rides shotgun?",
    es: "Viaje de 12 horas en coche, un asiento de copiloto. ¿Quién va delante?",
    options: [],
    socialSensitivity: 1,
    theoryTestable: true,
  }),
  q({
    id: "soc_phone_call",
    category: "social_choice",
    kinds: ["group_vote"],
    en: "Bad day. Who do you actually call?",
    es: "Día horrible. ¿A quién llamas de verdad?",
    options: [],
    socialSensitivity: 1,
    theoryTestable: true,
  }),
  q({
    id: "soc_business_partner",
    category: "social_choice",
    kinds: ["group_vote"],
    en: "You're starting a company. Who from this room is your co-founder?",
    es: "Vas a montar una empresa. ¿Quién de esta sala es tu cofundador?",
    options: [],
    theoryTestable: true,
  }),
  q({
    id: "soc_tell_first",
    category: "social_choice",
    kinds: ["group_vote"],
    en: "Huge news, good or bad. Who hears it first?",
    es: "Noticia enorme, buena o mala. ¿Quién se entera primero?",
    options: [],
    socialSensitivity: 1,
    theoryTestable: true,
  }),
  q({
    id: "soc_survive_zombie",
    category: "social_choice",
    kinds: ["group_vote"],
    en: "Zombie outbreak. Who do you want next to you?",
    es: "Brote zombi. ¿A quién quieres a tu lado?",
    options: [],
    theoryTestable: true,
  }),
  q({
    id: "soc_least_predictable",
    category: "social_choice",
    kinds: ["group_vote"],
    en: "Who here is most likely to surprise everyone tonight?",
    es: "¿Quién de aquí es más probable que sorprenda a todos esta noche?",
    options: [],
    socialSensitivity: 1,
  }),

  // ---------------- LIGHT SPICY ----------------
  q({
    id: "spicy_two_truths",
    category: "light_spicy",
    kinds: ["group_vote"],
    en: "Who here is the best liar?",
    es: "¿Quién de aquí miente mejor?",
    options: [],
    socialSensitivity: 2,
    theoryTestable: true,
  }),
  q({
    id: "spicy_secret_crush_generic",
    category: "light_spicy",
    kinds: ["group_vote"],
    en: "Who in this room is most obviously trying to impress someone tonight?",
    es: "¿Quién de esta sala está intentando impresionar a alguien esta noche de forma más evidente?",
    options: [],
    socialSensitivity: 3,
    theoryTestable: true,
  }),
  q({
    id: "spicy_drama",
    category: "light_spicy",
    kinds: ["group_vote"],
    en: "If there's drama in the group next month, who's at the center of it?",
    es: "Si el mes que viene hay salseo en el grupo, ¿quién está en el centro?",
    options: [],
    socialSensitivity: 3,
    theoryTestable: true,
  }),
  q({
    id: "spicy_ex_friends",
    category: "light_spicy",
    kinds: ["individual"],
    en: "Could you stay friends with someone after a serious falling out?",
    es: "¿Podrías seguir siendo amigo de alguien tras un piña seria?",
    options: [
      o("A", "Yes, I move past it", "Sí, lo supero", { patience: 0.5, cooperation: 0.4, loyalty: 0.3 }),
      o("B", "No, that's the end", "No, se acabó", { consistency: 0.4, contrarianism: 0.3, loyalty: -0.2 }),
    ],
    socialSensitivity: 2,
  }),
  q({
    id: "spicy_flirt_to_win",
    category: "light_spicy",
    kinds: ["individual"],
    en: "Would you use charm to get out of a losing position in a game?",
    es: "¿Usarías el encanto para salir de una posición perdedora en un juego?",
    options: [
      o("A", "Absolutely", "Por supuesto", { competitiveness: 0.6, individualism: 0.4, impulsivity: 0.3 }),
      o("B", "No, that's cheating", "No, eso es hacer trampa", { consistency: 0.5, competitiveness: -0.2 }),
    ],
    socialSensitivity: 2,
  }),
  q({
    id: "spicy_read_messages",
    category: "light_spicy",
    kinds: ["individual"],
    en: "Partner's phone lights up with a message. Do you look?",
    es: "El móvil de tu pareja se ilumina con un mensaje. ¿Lo miras?",
    options: [
      o("A", "I look", "Lo miro", { trust: -0.5, impulsivity: 0.5, individualism: 0.3 }),
      o("B", "I don't", "No lo miro", { trust: 0.5, consistency: 0.4 }),
    ],
    socialSensitivity: 2,
  }),
  q({
    id: "spicy_who_texts_back",
    category: "light_spicy",
    kinds: ["group_vote"],
    en: "Who here takes the longest to reply to messages on purpose?",
    es: "¿Quién de aquí tarda más en responder mensajes a propósito?",
    options: [],
    socialSensitivity: 2,
  }),

  // ---------------- BETRAYAL ----------------
  q({
    id: "betray_last_round",
    category: "betrayal",
    kinds: ["social_dilemma"],
    en: "Final round. Your ally trusts you completely. Betraying now wins you the game.",
    es: "Última ronda. Tu aliado confía en ti a ciegas. Traicionar ahora te da la partida.",
    options: [
      o("A", "Honor the alliance", "Honrar la alianza", { loyalty: 0.8, cooperation: 0.6, competitiveness: -0.3 }),
      o("B", "Betray to win", "Traicionar para ganar", { competitiveness: 0.8, individualism: 0.7, loyalty: -0.7 }),
    ],
    difficulty: 3,
    theoryTestable: true,
  }),
  q({
    id: "betray_warn",
    category: "betrayal",
    kinds: ["individual"],
    en: "You know someone is about to be betrayed. Warn them, even if it costs you?",
    es: "Sabes que alguien va a ser traicionado. ¿Le avisas, aunque te cueste?",
    options: [
      o("A", "Warn them", "Avisarle", { loyalty: 0.7, cooperation: 0.5, individualism: -0.3 }),
      o("B", "Stay out of it", "No meterme", { individualism: 0.5, consistency: 0.3 }),
    ],
    theoryTestable: true,
  }),
  q({
    id: "betray_forgive",
    category: "betrayal",
    kinds: ["individual"],
    en: "Someone betrayed you last game. This game, they offer an alliance. Accept?",
    es: "Alguien te traicionó la última partida. Esta partida te ofrece una alianza. ¿Aceptas?",
    options: [
      o("A", "Accept", "Aceptar", { cooperation: 0.5, patience: 0.4, trust: 0.4 }),
      o("B", "Refuse", "Rechazar", { consistency: 0.5, contrarianism: 0.3, trust: -0.4 }),
    ],
    theoryTestable: true,
  }),
  q({
    id: "betray_pre_emptive",
    category: "betrayal",
    kinds: ["social_dilemma"],
    en: "You suspect your partner will betray you next round. Strike first?",
    es: "Sospechas que tu compañero te traicionará la próxima ronda. ¿Golpear primero?",
    options: [
      o("A", "Wait and see", "Esperar y ver", { patience: 0.6, trust: 0.4, cooperation: 0.3 }),
      o("B", "Strike first", "Golpear primero", { impulsivity: 0.6, competitiveness: 0.5, trust: -0.5 }),
    ],
    difficulty: 3,
    theoryTestable: true,
  }),
  q({
    id: "betray_public",
    category: "betrayal",
    kinds: ["individual"],
    en: "If you betray someone, do you do it openly or let them figure it out?",
    es: "Si traicionas a alguien, ¿lo haces abiertamente o dejas que lo descubra?",
    options: [
      o("A", "Openly", "Abiertamente", { consistency: 0.4, competitiveness: 0.4, impulsivity: 0.3 }),
      o("B", "Let them find out", "Que lo descubra", { individualism: 0.5, patience: 0.3, loyalty: -0.3 }),
    ],
    socialSensitivity: 1,
  }),
  q({
    id: "betray_cost",
    category: "betrayal",
    kinds: ["social_dilemma"],
    en: "Betraying wins you +300 but the group will know it was you. Worth it?",
    es: "Traicionar te da +300 pero el grupo sabrá que fuiste tú. ¿Merece la pena?",
    options: [
      o("A", "Not worth it", "No merece la pena", { socialAlignment: 0.5, loyalty: 0.5, greed: -0.4 }),
      o("B", "Worth it", "Merece la pena", { greed: 0.7, individualism: 0.6, competitiveness: 0.5 }),
    ],
    difficulty: 3,
    theoryTestable: true,
  }),
  q({
    id: "betray_who",
    category: "betrayal",
    kinds: ["group_vote"],
    en: "Who in this room would betray the group to win?",
    es: "¿Quién de esta sala traicionaría al grupo para ganar?",
    options: [],
    socialSensitivity: 2,
    theoryTestable: true,
  }),

  // ---------------- ALLIANCE ----------------
  q({
    id: "ally_pick_partner",
    category: "alliance",
    kinds: ["group_vote", "trust"],
    en: "Pick one player to tie your score to for the next three rounds.",
    es: "Elige a un jugador para atar tu puntuación a la suya durante las próximas tres rondas.",
    options: [],
    theoryTestable: true,
  }),
  q({
    id: "ally_protect",
    category: "alliance",
    kinds: ["group_vote", "trust"],
    en: "Choose one player to protect you from losing 200 points this round.",
    es: "Elige a un jugador para que te proteja de perder 200 puntos esta ronda.",
    options: [],
    theoryTestable: true,
  }),
  q({
    id: "ally_share_reward",
    category: "alliance",
    kinds: ["group_vote"],
    en: "You just won 300 points. Choose one player to split it with.",
    es: "Acabas de ganar 300 puntos. Elige a un jugador con quien repartirlos.",
    options: [],
    theoryTestable: true,
  }),
  q({
    id: "ally_break_it",
    category: "alliance",
    kinds: ["social_dilemma"],
    en: "You and your ally both get +200 if you stay loyal. Break it and you get +500, they get 0.",
    es: "Tú y tu aliado ganáis +200 si seguís leales. Rómpela y ganas +500, el otro se queda a 0.",
    options: [
      o("A", "Stay loyal", "Seguir leal", { loyalty: 0.8, cooperation: 0.6 }),
      o("B", "Break it", "Romperla", { competitiveness: 0.7, greed: 0.6, loyalty: -0.7 }),
    ],
    difficulty: 3,
    theoryTestable: true,
  }),
  q({
    id: "ally_who_carries",
    category: "alliance",
    kinds: ["individual"],
    en: "In an alliance, are you usually the one carrying or the one being carried?",
    es: "En una alianza, ¿sueles ser quien tira o a quien tiran?",
    options: [
      o("A", "The one carrying", "Quien tira", { competitiveness: 0.5, individualism: 0.4, consistency: 0.4 }),
      o("B", "The one being carried", "A quien tiran", { cooperation: 0.4, loyalty: 0.4 }),
    ],
  }),
  q({
    id: "ally_two_offers",
    category: "alliance",
    kinds: ["individual"],
    en: "Two players offer you an alliance at the same time. You...",
    es: "Dos jugadores te ofrecen alianza a la vez. Tú...",
    options: [
      o("A", "Pick one and commit", "Elegir uno y comprometerme", { loyalty: 0.6, consistency: 0.5 }),
      o("B", "Say yes to both", "Decir sí a los dos", { individualism: 0.5, competitiveness: 0.4, loyalty: -0.4 }),
    ],
    theoryTestable: true,
  }),
  q({
    id: "ally_public_declare",
    category: "alliance",
    kinds: ["individual", "majority_minority"],
    en: "Declare your alliance publicly, or keep it secret?",
    es: "¿Declarar tu alianza en público, o mantenerla en secreto?",
    options: [
      o("A", "Public", "En público", { consistency: 0.5, socialAlignment: 0.4, competitiveness: 0.3 }),
      o("B", "Secret", "En secreto", { individualism: 0.5, patience: 0.4, contrarianism: 0.3 }),
    ],
  }),

  // ---------------- UNCERTAINTY ----------------
  q({
    id: "unc_hidden_rules",
    category: "uncertainty",
    kinds: ["individual"],
    en: "The game has hidden rules you'll only learn by breaking them. Do you probe or play safe?",
    es: "El juego tiene reglas ocultas que solo aprenderás rompiéndolas. ¿Tanteas o juegas seguro?",
    options: [
      o("A", "Probe them", "Tantearlas", { risk: 0.6, contrarianism: 0.4, impulsivity: 0.4 }),
      o("B", "Play safe", "Jugar seguro", { risk: -0.6, patience: 0.4, conformity: 0.3 }),
    ],
  }),
  q({
    id: "unc_mystery_box",
    category: "uncertainty",
    kinds: ["individual", "majority_minority"],
    en: "Keep 150 points, or trade them for a box worth anywhere from 0 to 400?",
    es: "¿Quedarte 150 puntos, o cambiarlos por una caja que vale entre 0 y 400?",
    options: [
      o("A", "Keep 150", "Quedarme 150", { risk: -0.7, patience: 0.2 }),
      o("B", "Trade for the box", "Cambiar por la caja", { risk: 0.7, impulsivity: 0.4, greed: 0.3 }),
    ],
  }),
  q({
    id: "unc_change_answer",
    category: "uncertainty",
    kinds: ["individual"],
    en: "You get one chance to change a past answer, but you won't be told if it helped. Use it?",
    es: "Tienes una oportunidad de cambiar una respuesta pasada, pero no sabrás si ayudó. ¿La usas?",
    options: [
      o("A", "Use it", "Usarla", { impulsivity: 0.5, risk: 0.4, consistency: -0.5 }),
      o("B", "Keep my answers", "Mantener mis respuestas", { consistency: 0.7, patience: 0.3 }),
    ],
  }),
  q({
    id: "unc_partial_info",
    category: "uncertainty",
    kinds: ["individual"],
    en: "You must decide now with half the information, or wait and lose your turn.",
    es: "Debes decidir ahora con la mitad de la información, o esperar y perder tu turno.",
    options: [
      o("A", "Decide now", "Decidir ahora", { impulsivity: 0.6, risk: 0.5, patience: -0.4 }),
      o("B", "Wait", "Esperar", { patience: 0.6, risk: -0.3, consistency: 0.3 }),
    ],
  }),
  q({
    id: "unc_rumor",
    category: "uncertainty",
    kinds: ["individual"],
    en: "A rumor says the scoring flips next round. Do you play as if it's true?",
    es: "Un rumor dice que la puntuación se invierte la próxima ronda. ¿Juegas como si fuera cierto?",
    options: [
      o("A", "Play as if true", "Jugar como si fuera cierto", { risk: 0.4, impulsivity: 0.4, trust: 0.3 }),
      o("B", "Ignore it", "Ignorarlo", { consistency: 0.5, contrarianism: 0.3, risk: -0.2 }),
    ],
  }),
  q({
    id: "unc_new_game",
    category: "uncertainty",
    kinds: ["individual"],
    en: "Someone suggests a game nobody knows the rules of. Your reaction?",
    es: "Alguien propone un juego cuyas reglas nadie conoce. ¿Tu reacción?",
    options: [
      o("A", "Let's try it", "Vamos a probarlo", { risk: 0.5, impulsivity: 0.4, contrarianism: 0.2 }),
      o("B", "Pick something we know", "Mejor algo que conozcamos", { risk: -0.5, patience: 0.3, conformity: 0.3 }),
    ],
    difficulty: 1,
  }),
  q({
    id: "unc_predict_self",
    category: "uncertainty",
    kinds: ["individual"],
    en: "Do you think the AI has already guessed your next choice?",
    es: "¿Crees que la IA ya ha adivinado tu próxima elección?",
    options: [
      o("A", "Probably yes", "Probablemente sí", { trust: 0.3, consistency: 0.3 }),
      o("B", "No chance", "Ni de broma", { contrarianism: 0.5, competitiveness: 0.4, individualism: 0.3 }),
    ],
    difficulty: 1,
  }),

  // ---------------- CONTRARIAN ----------------
  q({
    id: "con_unpopular_opinion",
    category: "contrarian",
    kinds: ["individual", "majority_minority"],
    en: "You hold an opinion the whole group disagrees with. Do you defend it or drop it?",
    es: "Tienes una opinión con la que todo el grupo está en contra. ¿La defiendes o la sueltas?",
    options: [
      o("A", "Defend it", "Defenderla", { contrarianism: 0.8, individualism: 0.5, conformity: -0.6 }),
      o("B", "Drop it", "Soltarla", { conformity: 0.6, socialAlignment: 0.4, patience: 0.3 }),
    ],
  }),
  q({
    id: "con_against_room",
    category: "contrarian",
    kinds: ["majority_minority"],
    en: "The room is clearly leaning toward A. Picking B could pay off more. You pick...",
    es: "La sala se inclina claramente por A. Elegir B podría dar más. Eliges...",
    options: [
      o("A", "A, with the room", "A, con la sala", { conformity: 0.8, socialAlignment: 0.6, risk: -0.2 }),
      o("B", "B, against the room", "B, contra la sala", { contrarianism: 0.8, individualism: 0.5, risk: 0.4 }),
    ],
    theoryTestable: true,
  }),
  q({
    id: "con_hype",
    category: "contrarian",
    kinds: ["individual"],
    en: "Everyone loves a new show. Do you watch it or avoid it just because of the hype?",
    es: "A todos les encanta una serie nueva. ¿La ves o la evitas justo por el hype?",
    options: [
      o("A", "Watch it", "Verla", { conformity: 0.6, socialAlignment: 0.4 }),
      o("B", "Avoid the hype", "Evitar el hype", { contrarianism: 0.7, individualism: 0.4 }),
    ],
    difficulty: 1,
  }),
  q({
    id: "con_devils_advocate",
    category: "contrarian",
    kinds: ["individual"],
    en: "In a group discussion, do you play devil's advocate for fun?",
    es: "En un debate de grupo, ¿haces de abogado del diablo por diversión?",
    options: [
      o("A", "Often", "A menudo", { contrarianism: 0.8, impulsivity: 0.3, competitiveness: 0.3 }),
      o("B", "Rarely", "Rara vez", { conformity: 0.4, socialAlignment: 0.4, patience: 0.3 }),
    ],
    difficulty: 1,
  }),
  q({
    id: "con_trend_bet",
    category: "contrarian",
    kinds: ["majority_minority"],
    en: "Everyone's betting on the favorite. Do you bet with them or against?",
    es: "Todos apuestan por el favorito. ¿Apuestas con ellos o en contra?",
    options: [
      o("A", "With them", "Con ellos", { conformity: 0.7, risk: -0.3 }),
      o("B", "Against", "En contra", { contrarianism: 0.7, risk: 0.6, competitiveness: 0.4 }),
    ],
  }),
  q({
    id: "con_change_mind",
    category: "contrarian",
    kinds: ["individual"],
    en: "How often do you change your mind because someone argued well?",
    es: "¿Con qué frecuencia cambias de opinión porque alguien argumentó bien?",
    options: [
      o("A", "Fairly often", "Bastante a menudo", { conformity: 0.5, patience: 0.4, consistency: -0.4 }),
      o("B", "Almost never", "Casi nunca", { consistency: 0.7, contrarianism: 0.5, individualism: 0.4 }),
    ],
    difficulty: 1,
  }),
  q({
    id: "con_rules",
    category: "contrarian",
    kinds: ["individual"],
    en: "A rule everyone follows seems pointless to you. Do you follow it anyway?",
    es: "Una norma que todos siguen te parece absurda. ¿La sigues igualmente?",
    options: [
      o("A", "Follow it", "Seguirla", { conformity: 0.7, patience: 0.3, socialAlignment: 0.4 }),
      o("B", "Ignore it", "Ignorarla", { contrarianism: 0.7, individualism: 0.5, impulsivity: 0.3 }),
    ],
  }),

  // ---------------- PREDICTION ROUNDS ----------------
  q({
    id: "pred_room_risky",
    category: "group_behavior",
    kinds: ["prediction"],
    en: "Will the majority of the room pick the risky option this round?",
    es: "¿La mayoría de la sala elegirá la opción arriesgada esta ronda?",
    options: [
      o("A", "Yes", "Sí", {}),
      o("B", "No", "No", {}),
    ],
    difficulty: 1,
  }),
  q({
    id: "pred_unanimous",
    category: "group_behavior",
    kinds: ["prediction"],
    en: "Will the room be unanimous on the next question?",
    es: "¿La sala será unánime en la próxima pregunta?",
    options: [
      o("A", "Yes", "Sí", {}),
      o("B", "No", "No", {}),
    ],
    difficulty: 1,
  }),
  q({
    id: "pred_someone_betrays",
    category: "betrayal",
    kinds: ["prediction"],
    en: "In the next dilemma, will at least one player betray?",
    es: "En el próximo dilema, ¿al menos un jugador traicionará?",
    options: [
      o("A", "Yes", "Sí", {}),
      o("B", "No", "No", {}),
    ],
  }),

  // ---------------- EXTRA INDIVIDUAL / MIXED ----------------
  q({
    id: "mix_apology",
    category: "social_choice",
    kinds: ["individual"],
    en: "You were clearly in the wrong. Apologize immediately or wait until it cools down?",
    es: "Estabas claramente equivocado. ¿Pedir perdón ya o esperar a que se enfríe?",
    options: [
      o("A", "Immediately", "Ya", { impulsivity: 0.3, consistency: 0.4, cooperation: 0.4 }),
      o("B", "Wait it out", "Esperar", { patience: 0.5, individualism: 0.3 }),
    ],
    difficulty: 1,
  }),
  q({
    id: "mix_plans_cancel",
    category: "social_choice",
    kinds: ["individual"],
    en: "Better plans come up after you already committed to something. You...",
    es: "Surge un plan mejor después de haberte comprometido a otra cosa. Tú...",
    options: [
      o("A", "Honor the first plan", "Honrar el primer plan", { loyalty: 0.6, consistency: 0.6, patience: 0.3 }),
      o("B", "Take the better plan", "Irte al plan mejor", { impulsivity: 0.5, individualism: 0.5, loyalty: -0.4 }),
    ],
  }),
  q({
    id: "mix_gift",
    category: "money",
    kinds: ["individual"],
    en: "Group gift for a friend. Do you push for the generous option or the reasonable one?",
    es: "Regalo de grupo para un amigo. ¿Empujas por la opción generosa o la razonable?",
    options: [
      o("A", "Generous", "Generosa", { cooperation: 0.5, greed: -0.4, socialAlignment: 0.4 }),
      o("B", "Reasonable", "Razonable", { consistency: 0.4, individualism: 0.3, greed: 0.2 }),
    ],
    difficulty: 1,
  }),
  q({
    id: "mix_queue_jump",
    category: "contrarian",
    kinds: ["individual", "majority_minority"],
    en: "The whole group jumps a barrier to skip a long queue. You...",
    es: "Todo el grupo salta una valla para saltarse una cola larga. Tú...",
    options: [
      o("A", "Follow them", "Seguirles", { conformity: 0.7, socialAlignment: 0.5, risk: 0.3 }),
      o("B", "Wait in line", "Esperar en la cola", { contrarianism: 0.5, consistency: 0.5, conformity: -0.5 }),
    ],
    socialSensitivity: 1,
  }),
  q({
    id: "mix_public_speaking",
    category: "competition",
    kinds: ["individual"],
    en: "Someone has to present to a big room. Do you volunteer?",
    es: "Alguien tiene que presentar ante una sala llena. ¿Te ofreces?",
    options: [
      o("A", "Volunteer", "Ofrecerme", { competitiveness: 0.5, risk: 0.4, individualism: 0.3 }),
      o("B", "Let someone else", "Que lo haga otro", { risk: -0.4, individualism: -0.2 }),
    ],
    difficulty: 1,
  }),
  q({
    id: "mix_save_or_spend_time",
    category: "strategy",
    kinds: ["individual"],
    en: "You have a free hour. Bank it for later or use it right now?",
    es: "Tienes una hora libre. ¿La guardas para luego o la usas ahora?",
    options: [
      o("A", "Bank it", "Guardarla", { patience: 0.6, consistency: 0.4, impulsivity: -0.4 }),
      o("B", "Use it now", "Usarla ahora", { impulsivity: 0.6, patience: -0.5 }),
    ],
    difficulty: 1,
  }),
  q({
    id: "mix_group_decision_speed",
    category: "group_behavior",
    kinds: ["individual"],
    en: "The group can't decide where to eat. You...",
    es: "El grupo no se decide dónde comer. Tú...",
    options: [
      o("A", "Just pick for everyone", "Decidir por todos", { individualism: 0.5, impulsivity: 0.4, competitiveness: 0.3 }),
      o("B", "Wait for consensus", "Esperar al consenso", { patience: 0.5, conformity: 0.4, cooperation: 0.3 }),
    ],
    difficulty: 1,
  }),
  q({
    id: "mix_win_streak",
    category: "risk",
    kinds: ["individual", "majority_minority"],
    en: "You're on a winning streak. Cash out now or keep riding it?",
    es: "Llevas una racha ganadora. ¿Retirar ahora o seguir la racha?",
    options: [
      o("A", "Cash out", "Retirar", { risk: -0.6, patience: 0.3, consistency: 0.3 }),
      o("B", "Keep riding", "Seguir", { risk: 0.7, impulsivity: 0.4, greed: 0.4 }),
    ],
  }),
  q({
    id: "mix_favor",
    category: "loyalty",
    kinds: ["individual"],
    en: "A friend asks for a favor that's a real hassle. Do you say yes?",
    es: "Un amigo te pide un favor que es un marrón de verdad. ¿Dices que sí?",
    options: [
      o("A", "Yes", "Sí", { loyalty: 0.7, cooperation: 0.5, individualism: -0.3 }),
      o("B", "Make an excuse", "Poner una excusa", { individualism: 0.5, loyalty: -0.3 }),
    ],
    difficulty: 1,
  }),
  q({
    id: "mix_first_offer",
    category: "money",
    kinds: ["individual"],
    en: "Selling something online. Take the first fair offer or hold out for more?",
    es: "Vendes algo por internet. ¿Aceptas la primera oferta justa o aguantas por más?",
    options: [
      o("A", "Take the first offer", "Aceptar la primera", { patience: -0.3, risk: -0.4, impulsivity: 0.3 }),
      o("B", "Hold out", "Aguantar", { patience: 0.5, greed: 0.4, risk: 0.3 }),
    ],
    difficulty: 1,
  }),
  q({
    id: "mix_group_blame",
    category: "group_behavior",
    kinds: ["individual"],
    en: "The group failed a task together. When asked, you...",
    es: "El grupo falló una tarea juntos. Cuando preguntan, tú...",
    options: [
      o("A", "Take shared responsibility", "Asumir la parte de todos", { cooperation: 0.6, loyalty: 0.5, consistency: 0.3 }),
      o("B", "Clarify it wasn't your part", "Aclarar que no fue tu parte", { individualism: 0.6, consistency: 0.4, loyalty: -0.3 }),
    ],
  }),
  q({
    id: "mix_new_person",
    category: "social_choice",
    kinds: ["individual"],
    en: "A new person joins the group. Are you the one who makes them feel welcome?",
    es: "Alguien nuevo se une al grupo. ¿Eres tú quien le hace sentir bienvenido?",
    options: [
      o("A", "Usually me", "Normalmente yo", { cooperation: 0.5, socialAlignment: 0.5, loyalty: 0.3 }),
      o("B", "I hang back", "Me mantengo atrás", { individualism: 0.4, patience: 0.3 }),
    ],
    difficulty: 1,
  }),
  q({
    id: "mix_break_rule_for_friend",
    category: "loyalty",
    kinds: ["individual"],
    en: "Bending a rule would really help a friend and probably won't be noticed. Do it?",
    es: "Saltarte una norma ayudaría mucho a un amigo y seguramente no se note. ¿Lo haces?",
    options: [
      o("A", "Do it", "Hacerlo", { loyalty: 0.7, risk: 0.4, contrarianism: 0.3 }),
      o("B", "Don't", "No hacerlo", { consistency: 0.6, conformity: 0.4, loyalty: -0.3 }),
    ],
  }),
  q({
    id: "mix_competitive_board_game",
    category: "competition",
    kinds: ["individual"],
    en: "Family board game night. Do you let the youngest win?",
    es: "Noche de juegos de mesa en familia. ¿Dejas ganar al más pequeño?",
    options: [
      o("A", "Let them win", "Dejarle ganar", { cooperation: 0.5, competitiveness: -0.5, loyalty: 0.3 }),
      o("B", "No mercy", "Sin piedad", { competitiveness: 0.8, consistency: 0.3 }),
    ],
    difficulty: 1,
  }),
  q({
    id: "mix_secret_vote",
    category: "trust",
    kinds: ["group_vote"],
    en: "Who here would you trust to count the votes fairly?",
    es: "¿En quién de aquí confiarías para contar los votos de forma justa?",
    options: [],
    theoryTestable: true,
  }),
  q({
    id: "mix_who_competitive",
    category: "competition",
    kinds: ["group_vote"],
    en: "Who here hates losing the most?",
    es: "¿Quién de aquí es el peor perdedor?",
    options: [],
    socialSensitivity: 1,
    theoryTestable: true,
  }),
  q({
    id: "mix_who_generous",
    category: "money",
    kinds: ["group_vote"],
    en: "Who here is the most generous with money?",
    es: "¿Quién de aquí es el más generoso con el dinero?",
    options: [],
    theoryTestable: true,
  }),
  q({
    id: "mix_who_follows",
    category: "group_behavior",
    kinds: ["group_vote"],
    en: "Who here most often just goes along with the group?",
    es: "¿Quién de aquí sigue más a menudo la corriente del grupo?",
    options: [],
    socialSensitivity: 1,
    theoryTestable: true,
  }),
  q({
    id: "mix_who_contrarian",
    category: "contrarian",
    kinds: ["group_vote"],
    en: "Who here disagrees just to disagree?",
    es: "¿Quién de aquí lleva la contraria solo por llevarla?",
    options: [],
    socialSensitivity: 1,
    theoryTestable: true,
  }),
  q({
    id: "mix_who_planner",
    category: "strategy",
    kinds: ["group_vote"],
    en: "Who here is always three moves ahead?",
    es: "¿Quién de aquí va siempre tres jugadas por delante?",
    options: [],
    theoryTestable: true,
  }),
  q({
    id: "mix_who_impulsive",
    category: "uncertainty",
    kinds: ["group_vote"],
    en: "Who here decides fastest, for better or worse?",
    es: "¿Quién de aquí decide más rápido, para bien o para mal?",
    options: [],
    socialSensitivity: 1,
  }),
  q({
    id: "mix_reward_or_revenge",
    category: "strategy",
    kinds: ["individual"],
    en: "You can either gain 100 points or make the person who wronged you lose 100. Pick.",
    es: "Puedes ganar 100 puntos o hacer que quien te perjudicó pierda 100. Elige.",
    options: [
      o("A", "Gain 100", "Ganar 100", { individualism: 0.4, greed: 0.4, patience: 0.3 }),
      o("B", "Make them lose 100", "Que pierda 100", { competitiveness: 0.7, contrarianism: 0.4, impulsivity: 0.3 }),
    ],
  }),
  q({
    id: "mix_group_secret_task",
    category: "cooperation",
    kinds: ["social_dilemma"],
    en: "You and one player are secretly told: cooperate and the whole group gains. Only you two know.",
    es: "A ti y a otro jugador os dicen en secreto: cooperad y todo el grupo gana. Solo lo sabéis vosotros dos.",
    options: [
      o("A", "Cooperate quietly", "Cooperar en silencio", { cooperation: 0.7, loyalty: 0.4, socialAlignment: 0.4 }),
      o("B", "Keep the gain hidden", "Guardarme la ventaja", { individualism: 0.6, greed: 0.5, cooperation: -0.4 }),
    ],
    theoryTestable: true,
  }),
  q({
    id: "mix_endurance",
    category: "risk",
    kinds: ["individual"],
    en: "A challenge: the last person still playing wins big, but every extra minute costs points.",
    es: "Un reto: la última persona que siga jugando gana a lo grande, pero cada minuto extra cuesta puntos.",
    options: [
      o("A", "Drop out early and safe", "Retirarme pronto y seguro", { risk: -0.6, patience: 0.3, competitiveness: -0.2 }),
      o("B", "Outlast everyone", "Aguantar más que nadie", { competitiveness: 0.8, risk: 0.6, patience: 0.4 }),
    ],
  }),
  q({
    id: "mix_trust_stranger",
    category: "trust",
    kinds: ["individual"],
    en: "A stranger asks you to watch their bag 'for two minutes'. Do you agree?",
    es: "Un desconocido te pide que le vigiles la mochila 'dos minutos'. ¿Aceptas?",
    options: [
      o("A", "Sure", "Claro", { trust: 0.6, cooperation: 0.4 }),
      o("B", "No", "No", { trust: -0.5, individualism: 0.3, risk: -0.3 }),
    ],
    difficulty: 1,
  }),
  q({
    id: "mix_group_split_teams",
    category: "alliance",
    kinds: ["group_vote"],
    en: "Teams are being picked. Who do you want as your first pick?",
    es: "Se están eligiendo equipos. ¿A quién quieres como primera elección?",
    options: [],
    theoryTestable: true,
  }),
  q({
    id: "mix_call_out",
    category: "group_behavior",
    kinds: ["individual"],
    en: "Someone in the group keeps interrupting everyone. Do you call it out?",
    es: "Alguien del grupo no para de interrumpir a todos. ¿Lo dices en voz alta?",
    options: [
      o("A", "Call it out", "Decirlo", { contrarianism: 0.5, consistency: 0.4, individualism: 0.4 }),
      o("B", "Let it slide", "Dejarlo pasar", { conformity: 0.5, patience: 0.4, socialAlignment: 0.3 }),
    ],
    socialSensitivity: 1,
  }),
  q({
    id: "mix_share_food",
    category: "cooperation",
    kinds: ["individual"],
    en: "You ordered something amazing. A friend asks for a bite. Real answer?",
    es: "Has pedido algo increíble. Un amigo te pide un bocado. ¿Respuesta sincera?",
    options: [
      o("A", "Of course, dig in", "Claro, coge", { cooperation: 0.6, greed: -0.4, loyalty: 0.3 }),
      o("B", "One small bite", "Un bocado pequeño", { greed: 0.5, individualism: 0.4 }),
    ],
    difficulty: 1,
  }),
  q({
    id: "mix_admit_wrong_publicly",
    category: "contrarian",
    kinds: ["individual"],
    en: "You argued hard for something and turned out wrong. Do you admit it to the group?",
    es: "Defendiste algo con fuerza y resultó que estabas equivocado. ¿Lo admites ante el grupo?",
    options: [
      o("A", "Admit it clearly", "Admitirlo claramente", { consistency: 0.6, cooperation: 0.4, competitiveness: -0.3 }),
      o("B", "Downplay it", "Quitarle importancia", { competitiveness: 0.5, individualism: 0.4, consistency: -0.3 }),
    ],
  }),
  q({
    id: "mix_long_odds",
    category: "risk",
    kinds: ["majority_minority", "individual"],
    en: "10% chance of 1000 points, or 90% chance of 100 points?",
    es: "¿10% de opción a 1000 puntos, o 90% de opción a 100 puntos?",
    options: [
      o("A", "90% of 100", "90% de 100", { risk: -0.7, patience: 0.2 }),
      o("B", "10% of 1000", "10% de 1000", { risk: 0.8, greed: 0.4, competitiveness: 0.3 }),
    ],
  }),
  q({
    id: "mix_who_leader",
    category: "trust",
    kinds: ["group_vote", "trust"],
    en: "If this group had to pick a leader right now, who?",
    es: "Si este grupo tuviera que elegir un líder ahora mismo, ¿quién?",
    options: [],
    theoryTestable: true,
  }),
  q({
    id: "mix_who_wildcard",
    category: "uncertainty",
    kinds: ["group_vote"],
    en: "Who here is the biggest wildcard in this game?",
    es: "¿Quién de aquí es el mayor comodín de esta partida?",
    options: [],
    socialSensitivity: 1,
  }),
  q({
    id: "mix_split_or_steal_final",
    category: "betrayal",
    kinds: ["social_dilemma"],
    en: "Split & Steal for the jackpot. Both split: +250 each. One steals: that player takes 500. Both steal: 0.",
    es: "Repartir o Robar por el bote. Ambos reparten: +250 cada uno. Uno roba: ese jugador se lleva 500. Ambos roban: 0.",
    options: [
      o("A", "Split", "Repartir", { cooperation: 0.7, trust: 0.5, loyalty: 0.4 }),
      o("B", "Steal", "Robar", { greed: 0.8, competitiveness: 0.6, cooperation: -0.7 }),
    ],
    difficulty: 3,
    theoryTestable: true,
  }),
  q({
    id: "mix_defend_choice",
    category: "contrarian",
    kinds: ["individual", "majority_minority"],
    en: "You'll have to explain your choice out loud afterward. Does that change it?",
    es: "Tendrás que explicar tu elección en voz alta después. ¿Eso la cambia?",
    options: [
      o("A", "Yes, I'd soften it", "Sí, la suavizaría", { conformity: 0.6, socialAlignment: 0.5, consistency: -0.3 }),
      o("B", "No, same choice", "No, la misma", { consistency: 0.6, individualism: 0.4, contrarianism: 0.3 }),
    ],
  }),
  q({
    id: "mix_group_gift_money",
    category: "money",
    kinds: ["social_dilemma"],
    en: "Everyone secretly contributes to a pot. It's doubled and split evenly. Contribute fully?",
    es: "Todos aportáis en secreto a un bote. Se dobla y se reparte a partes iguales. ¿Aportas todo?",
    options: [
      o("A", "Contribute fully", "Aportar todo", { cooperation: 0.8, trust: 0.5, greed: -0.4 }),
      o("B", "Hold most of it back", "Guardarme casi todo", { individualism: 0.6, greed: 0.6, trust: -0.4 }),
    ],
    difficulty: 3,
    theoryTestable: true,
  }),
  q({
    id: "mix_patience_test",
    category: "uncertainty",
    kinds: ["individual"],
    en: "Press now for 50 points, or wait 20 seconds for a chance at 200.",
    es: "Pulsa ahora por 50 puntos, o espera 20 segundos por una opción a 200.",
    options: [
      o("A", "Press now", "Pulsar ahora", { patience: -0.7, impulsivity: 0.7, risk: -0.2 }),
      o("B", "Wait", "Esperar", { patience: 0.8, risk: 0.3, consistency: 0.3 }),
    ],
    difficulty: 1,
  }),
  q({
    id: "mix_who_honest",
    category: "trust",
    kinds: ["group_vote"],
    en: "Who here tells you the truth even when you don't want to hear it?",
    es: "¿Quién de aquí te dice la verdad aunque no quieras oírla?",
    options: [],
    theoryTestable: true,
  }),
  q({
    id: "mix_take_blame",
    category: "loyalty",
    kinds: ["social_dilemma"],
    en: "You and a partner both risk a penalty. You can take the full hit alone to clear them. Do you?",
    es: "Tú y un compañero arriesgáis una penalización. Puedes llevarte el golpe entero tú solo para librarle. ¿Lo haces?",
    options: [
      o("A", "Take it alone", "Llevármelo solo", { loyalty: 0.9, cooperation: 0.6, individualism: -0.5 }),
      o("B", "Split the hit", "Repartir el golpe", { consistency: 0.4, individualism: 0.4 }),
    ],
    theoryTestable: true,
  }),
  q({
    id: "mix_early_leave",
    category: "group_behavior",
    kinds: ["individual"],
    en: "You want to leave the party. Do you announce it or slip out quietly?",
    es: "Quieres irte de la fiesta. ¿Lo anuncias o te escabulles sin decir nada?",
    options: [
      o("A", "Announce it", "Anunciarlo", { socialAlignment: 0.4, consistency: 0.4, loyalty: 0.3 }),
      o("B", "Slip out", "Escabullirme", { individualism: 0.5, contrarianism: 0.3, impulsivity: 0.3 }),
    ],
    difficulty: 1,
  }),
  q({
    id: "mix_bet_on_friend",
    category: "trust",
    kinds: ["prediction"],
    en: "Will the player to your left pick the same option as you this round?",
    es: "¿El jugador a tu izquierda elegirá la misma opción que tú esta ronda?",
    options: [
      o("A", "Yes", "Sí", {}),
      o("B", "No", "No", {}),
    ],
    difficulty: 1,
  }),
  q({
    id: "mix_group_dare",
    category: "risk",
    kinds: ["individual", "majority_minority"],
    en: "The group votes on a dare for one person. Would you accept being that person?",
    es: "El grupo vota un reto para una persona. ¿Aceptarías ser esa persona?",
    options: [
      o("A", "Yes, bring it", "Sí, adelante", { risk: 0.7, competitiveness: 0.5, impulsivity: 0.4 }),
      o("B", "No way", "Ni hablar", { risk: -0.6, conformity: -0.2 }),
    ],
    socialSensitivity: 1,
  }),
  q({
    id: "mix_keep_score",
    category: "competition",
    kinds: ["individual"],
    en: "Casual game with friends. Do you secretly keep score anyway?",
    es: "Partida informal con amigos. ¿Llevas la cuenta en secreto igualmente?",
    options: [
      o("A", "Always", "Siempre", { competitiveness: 0.7, consistency: 0.4, individualism: 0.3 }),
      o("B", "Never", "Nunca", { competitiveness: -0.4, cooperation: 0.3 }),
    ],
    difficulty: 1,
  }),
  q({
    id: "mix_final_trust",
    category: "trust",
    kinds: ["trust", "group_vote"],
    en: "One player will decide how your final points are split. Who do you hand that power to?",
    es: "Un jugador decidirá cómo se reparten tus puntos finales. ¿A quién le das ese poder?",
    options: [],
    theoryTestable: true,
  }),

  // ═══════════ COMPAT_PROBE — same answer = chemistry ═══════════
  // No behavioral tags: these measure taste/values, and the engine
  // pairs whoever answered identically.
  q({
    id: "cp_night_out",
    category: "social_choice",
    kinds: ["compat_probe"],
    en: "The perfect night:",
    es: "La noche perfecta:",
    options: [
      o("A", "Loud, packed, out till dawn", "Ruidosa, llena, hasta el amanecer"),
      o("B", "Small group, good conversation", "Grupo pequeño, buena conversación"),
      o("C", "Just me and a screen", "Yo solo y una pantalla"),
    ],
    difficulty: 1,
  }),
  q({
    id: "cp_argue",
    category: "social_choice",
    kinds: ["compat_probe"],
    en: "In an argument you'd rather be:",
    es: "En una discusión prefieres:",
    options: [
      o("A", "Right", "Tener razón"),
      o("B", "Kind", "Ser amable"),
      o("C", "Done with it", "Que se acabe ya"),
    ],
    difficulty: 1,
  }),
  q({
    id: "cp_money_love",
    category: "social_choice",
    kinds: ["compat_probe"],
    en: "Bigger red flag in someone:",
    es: "Peor red flag en alguien:",
    options: [
      o("A", "Stingy with money", "Rácano con el dinero"),
      o("B", "Rude to waiters", "Borde con los camareros"),
      o("C", "Never on time", "Nunca puntual"),
    ],
    difficulty: 1,
    socialSensitivity: 1,
  }),
  q({
    id: "cp_plans",
    category: "social_choice",
    kinds: ["compat_probe"],
    en: "Someone cancels plans last minute. You feel:",
    es: "Alguien te cancela un plan a última hora. Sientes:",
    options: [
      o("A", "Relieved, honestly", "Alivio, sinceramente"),
      o("B", "Annoyed", "Fastidio"),
      o("C", "Nothing, it happens", "Nada, pasa"),
    ],
    difficulty: 1,
  }),
  q({
    id: "cp_trip",
    category: "social_choice",
    kinds: ["compat_probe"],
    en: "Dream trip:",
    es: "Viaje soñado:",
    options: [
      o("A", "City, chaos, nightlife", "Ciudad, caos, vida nocturna"),
      o("B", "Beach, nothing to do", "Playa, nada que hacer"),
      o("C", "Mountains, no signal", "Montaña, sin cobertura"),
    ],
    difficulty: 1,
  }),
  q({
    id: "cp_love_language",
    category: "light_spicy",
    kinds: ["compat_probe"],
    en: "You show you like someone by:",
    es: "Demuestras que alguien te gusta:",
    options: [
      o("A", "Teasing them non-stop", "Picándole sin parar"),
      o("B", "Going quiet and weird", "Poniéndote raro y callado"),
      o("C", "Being very obvious", "Siendo muy evidente"),
    ],
    difficulty: 1,
    socialSensitivity: 2,
  }),
  q({
    id: "cp_ick",
    category: "light_spicy",
    kinds: ["compat_probe"],
    en: "Instant turn-off:",
    es: "Corta el rollo al instante:",
    options: [
      o("A", "Talks about their ex", "Habla de su ex"),
      o("B", "No sense of humour", "Sin sentido del humor"),
      o("C", "Too keen too fast", "Demasiado intenso demasiado pronto"),
    ],
    difficulty: 1,
    socialSensitivity: 2,
  }),
  q({
    id: "cp_first_move",
    category: "light_spicy",
    kinds: ["compat_probe"],
    en: "Making the first move is:",
    es: "Dar el primer paso es:",
    options: [
      o("A", "Exciting", "Emocionante"),
      o("B", "Terrifying", "Aterrador"),
      o("C", "Someone else's job", "Cosa de otra persona"),
    ],
    difficulty: 1,
    socialSensitivity: 2,
  }),
  q({
    id: "cp_texting",
    category: "social_choice",
    kinds: ["compat_probe"],
    en: "Your texting style:",
    es: "Tu estilo escribiendo:",
    options: [
      o("A", "Instant replies", "Respondo al momento"),
      o("B", "Hours later, one word", "Horas después, una palabra"),
      o("C", "Voice notes only", "Solo notas de voz"),
    ],
    difficulty: 1,
  }),
  q({
    id: "cp_secret",
    category: "light_spicy",
    kinds: ["compat_probe"],
    en: "A secret is safe with you:",
    es: "Un secreto está a salvo contigo:",
    options: [
      o("A", "Always", "Siempre"),
      o("B", "Unless it's really good", "Salvo que sea muy bueno"),
      o("C", "Absolutely not", "Para nada"),
    ],
    difficulty: 1,
    socialSensitivity: 1,
  }),
  q({
    id: "cp_conflict_style",
    category: "social_choice",
    kinds: ["compat_probe"],
    en: "When you're upset with someone:",
    es: "Cuando te enfadas con alguien:",
    options: [
      o("A", "I say it straight away", "Lo digo al momento"),
      o("B", "I go cold for a while", "Me pongo distante un tiempo"),
      o("C", "I pretend it's fine", "Hago como que no pasa nada"),
    ],
    difficulty: 1,
    socialSensitivity: 1,
  }),
  q({
    id: "cp_group_role",
    category: "group_behavior",
    kinds: ["compat_probe"],
    en: "In a group you're the one who:",
    es: "En un grupo eres quien:",
    options: [
      o("A", "Plans everything", "Organiza todo"),
      o("B", "Shows up and vibes", "Aparece y fluye"),
      o("C", "Causes the chaos", "Provoca el caos"),
    ],
    difficulty: 1,
  }),

  // ═══════════ ACCUSATION — point at a player ═══════════
  q({
    id: "acc_liar",
    category: "light_spicy",
    kinds: ["accusation"],
    en: "Who here is lying the most tonight?",
    es: "¿Quién de aquí está mintiendo más esta noche?",
    options: [],
    socialSensitivity: 2,
  }),
  q({
    id: "acc_flirt",
    category: "light_spicy",
    kinds: ["accusation"],
    en: "Who's trying hardest to impress someone in this room?",
    es: "¿Quién se está esforzando más por impresionar a alguien de esta sala?",
    options: [],
    socialSensitivity: 3,
  }),
  q({
    id: "acc_drama",
    category: "light_spicy",
    kinds: ["accusation"],
    en: "Who would start the drama if this group fell apart?",
    es: "¿Quién montaría el pollo si este grupo se rompiera?",
    options: [],
    socialSensitivity: 3,
  }),
  q({
    id: "acc_snake",
    category: "betrayal",
    kinds: ["accusation"],
    en: "Who here would sell the rest of you out to win?",
    es: "¿Quién de aquí os vendería a los demás por ganar?",
    options: [],
    socialSensitivity: 2,
  }),
  q({
    id: "acc_secret_mission",
    category: "betrayal",
    kinds: ["accusation"],
    en: "Who is playing their own game right now?",
    es: "¿Quién está jugando a su propio juego ahora mismo?",
    options: [],
    socialSensitivity: 2,
  }),
  q({
    id: "acc_faker",
    category: "group_behavior",
    kinds: ["accusation"],
    en: "Who's just agreeing with everything to stay safe?",
    es: "¿Quién dice que sí a todo solo para no mojarse?",
    options: [],
    socialSensitivity: 2,
  }),
  q({
    id: "acc_wildcard",
    category: "uncertainty",
    kinds: ["accusation"],
    en: "Who has no idea what they're doing but it's working?",
    es: "¿Quién no tiene ni idea de lo que hace pero le está saliendo bien?",
    options: [],
    socialSensitivity: 1,
  }),
  q({
    id: "acc_softest",
    category: "trust",
    kinds: ["accusation"],
    en: "Who would crack first under real pressure?",
    es: "¿Quién se rompería primero bajo presión de verdad?",
    options: [],
    socialSensitivity: 2,
  }),

  // ═══════════ EXTRA LIGHT SPICY (individual + vote) ═══════════
  q({
    id: "spicy_reconnect_ex",
    category: "light_spicy",
    kinds: ["individual"],
    en: "An ex texts 'hey, been thinking about you'. You:",
    es: "Un ex te escribe 'hey, he estado pensando en ti'. Tú:",
    options: [
      o("A", "Reply right away", "Respondes al momento", { impulsivity: 0.6, risk: 0.4 }),
      o("B", "Leave it on read", "Lo dejas en visto", { consistency: 0.4, patience: 0.4 }),
      o("C", "Screenshot it to the group chat", "Captura al grupo", { socialAlignment: 0.5, loyalty: -0.2, impulsivity: 0.4 }),
    ],
    socialSensitivity: 3,
  }),
  q({
    id: "spicy_group_crush",
    category: "light_spicy",
    kinds: ["individual"],
    en: "You realise two of your friends like each other. You:",
    es: "Te das cuenta de que dos amigos tuyos se gustan. Tú:",
    options: [
      o("A", "Play matchmaker", "Haces de celestina", { socialAlignment: 0.5, impulsivity: 0.4 }),
      o("B", "Say nothing, watch it unfold", "No dices nada y observas", { patience: 0.6, individualism: 0.3 }),
      o("C", "Tell everyone", "Se lo cuentas a todos", { loyalty: -0.4, impulsivity: 0.6 }),
    ],
    socialSensitivity: 3,
  }),
  q({
    id: "spicy_jealous",
    category: "light_spicy",
    kinds: ["individual"],
    en: "Your closest friend gets a new best friend. You feel:",
    es: "Tu mejor amigo se echa un nuevo mejor amigo. Sientes:",
    options: [
      o("A", "Genuinely happy", "Alegría de verdad", { cooperation: 0.5, trust: 0.4 }),
      o("B", "A little threatened", "Un poco amenazado", { individualism: 0.4, competitiveness: 0.4 }),
      o("C", "Ready to compete", "Listo para competir", { competitiveness: 0.7, loyalty: 0.3 }),
    ],
    socialSensitivity: 2,
  }),
  q({
    id: "spicy_who_first_kiss_story",
    category: "light_spicy",
    kinds: ["accusation"],
    en: "Whose dating life would make the best TV show?",
    es: "¿La vida amorosa de quién sería la mejor serie?",
    options: [],
    socialSensitivity: 3,
  }),
  q({
    id: "spicy_overshare",
    category: "light_spicy",
    kinds: ["accusation"],
    en: "Who overshares the second they get comfortable?",
    es: "¿Quién cuenta demasiado en cuanto coge confianza?",
    options: [],
    socialSensitivity: 2,
  }),
];

// ---------- Indexes / helpers ----------

export const QUESTIONS_BY_ID: Record<string, Question> = Object.fromEntries(
  QUESTIONS.map((q) => [q.id, q]),
);

export function questionsForKind(kind: RoundKind): Question[] {
  return QUESTIONS.filter((q) => q.kinds.includes(kind));
}

/** Player-target rounds have their options built at runtime from the roster. */
export function isPlayerTargetKind(kind: RoundKind): boolean {
  return kind === "group_vote" || kind === "trust" || kind === "accusation";
}

export const QUESTION_COUNT = QUESTIONS.length;
